data_path    : "/home/mindful/Documents/data/kube_dataset/preprocessed_samples"
buffer_path  : "/home/mindful/Documents/data/buffer_studies/slices"
#data_path    : "/Users/andyvarner/Documents/data/kube_dataset/preprocessed_samples"

# choice=0 to return value of center pixel, choice=1 to return average
choice : 1

# size of the simulation cell in microns
full_size : 2.04
crop_size :

# integer value number of pixels per image
full_pix  :
crop_pix  :

# an np.meshgrid object, used to plot images on a plt.pcolormesh plot
X_grid    :
Y_grid    :

X_grid_crop :
Y_grid_crop : 

#for getting cropped image dimensions
start_row :
end_row :

start_col :
end_col :
